<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tf</string>
		<string>tfvars</string>
	</array>
	<key>name</key>
	<string>Terraform</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*([^*]|\*[^\/])*</string>
					<key>end</key>
					<string>\*\/</string>
					<key>name</key>
					<string>comment.block.terraform</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-remark</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\#</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.number-sign.terraform</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-remark</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment-remark</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bold.comment.terraform</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(TODO|FIXME|BUG|\!\!\!):?</string>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heredoc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#resource-definition</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.terraform</string>
				</dict>
			</array>
		</dict>
		<key>heredoc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;&lt;(.+)$</string>
					<key>end</key>
					<string>^\1</string>
					<key>name</key>
					<string>string.quoted.other.terraform</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\'\'(\$|\'|\\.)</string>
							<key>name</key>
							<string>constant.character.escape.terraform</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-quoted</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>begin</key>
			<string>\$\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character.begin.terraform</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.interpolated.terraform</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.character.end.terraform</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(concat|file|join|lookup|element)\b</string>
					<key>name</key>
					<string>support.function.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(var|path|count)\.\b</string>
					<key>name</key>
					<string>support.scope.terraform</string>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>parens</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>resource-definition</key>
		<dict>
			<key>begin</key>
			<string>\b(resource|provisioner)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.terraform</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\{</string>
			<key>name</key>
			<string>function.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\'\'</string>
					<key>end</key>
					<string>\'\'(?!\$|\'|\\.)</string>
					<key>name</key>
					<string>string.quoted.other.terraform</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\'\'(\$|\'|\\.)</string>
							<key>name</key>
							<string>constant.character.escape.terraform</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-quoted</string>
				</dict>
			</array>
		</dict>
		<key>string-quoted</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.terraform</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.terraform</string>
	<key>uuid</key>
	<string>2a4be4fe-5d3a-7841-6ae4-b1b8ab60fd10</string>
</dict>
</plist>
